name: roomiefind
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  # Lógica y Base de Datos
  supabase_flutter: ^2.12.4
  provider: ^6.1.5

  # Funcionalidades añadidas
  image_picker: ^1.0.7

  flutter_map: ^8.3.0
  latlong2: ^0.9.1
  http: ^1.6.0
  google_maps_flutter: ^2.17.0
  shared_preferences: ^2.5.5
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/photos/Logo.png